/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ta8;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.BorderLayout;
import javax.swing.JFrame;
import com.formdev.flatlaf.extras.FlatSVGIcon;


/**
 *
 * @author USER
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    private FlatSVGIcon Home;
    private FlatSVGIcon Kaset;
    private FlatSVGIcon Kriteria;
    private FlatSVGIcon Sub;
    private FlatSVGIcon Penilaian;
    private FlatSVGIcon Hitung;
    private FlatSVGIcon Hasil;
    private FlatSVGIcon Print;
    public Dashboard() {
        initComponents();
        setLocationRelativeTo(null);
        jLogout.setCursor(new Cursor(Cursor.HAND_CURSOR));
      
       Home = new FlatSVGIcon("img/rumah.svg", 26, 26); // Menyimpan ikon home
       jhome.setIcon(Home);
       Kaset = new FlatSVGIcon("img/Cdgame.svg", 26, 26); // Menyimpan ikon home
       jkasett.setIcon(Kaset);
       Kriteria = new FlatSVGIcon("img/datakriteria.svg", 26, 26); // Menyimpan ikon home
       jkriteriaa.setIcon(Kriteria);
       Sub = new FlatSVGIcon("img/iconChest.svg", 26, 26); // Menyimpan ikon home
       jsub.setIcon(Sub);
       Penilaian = new FlatSVGIcon("img/iconpenilaian.svg", 26, 26); // Menyimpan ikon home
       jnilaikaset.setIcon(Penilaian);
       Hitung = new FlatSVGIcon("img/Iconkalku.svg", 26, 26); // Menyimpan ikon home
       jhitung.setIcon(Hitung);
       Hasil = new FlatSVGIcon("img/seleksi.svg", 26, 26); // Menyimpan ikon home
       jkalkulator.setIcon(Hasil);
       Print = new FlatSVGIcon("img/Printer.svg", 26, 26); // Menyimpan ikon home
       jprint.setIcon(Print);
    }

   private void setIconColor(FlatSVGIcon icon, Color color) {
        icon.setColorFilter(new FlatSVGIcon.ColorFilter() {
            @Override
            public Color filter(Color c) {
                return color;
            }
        });
    }

    private void setMainPanel(javax.swing.JPanel panel) {
      mainPanel.removeAll();
     mainPanel.setLayout(new BorderLayout());
    mainPanel.add(panel);
    mainPanel.revalidate();
     mainPanel.repaint();
}
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGabung1 = new ta8.PanelGabung();
        pn_dashboard = new ta8.PanelGabung();
        pn_hover = new ta8.PanelGabung();
        jdashboard = new javax.swing.JLabel();
        jhome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pn_dashboard2 = new ta8.PanelGabung();
        pn_hover2 = new ta8.PanelGabung();
        jkaset = new javax.swing.JLabel();
        jkasett = new javax.swing.JLabel();
        pn_dashboard3 = new ta8.PanelGabung();
        pn_hover3 = new ta8.PanelGabung();
        jkriteria = new javax.swing.JLabel();
        jkriteriaa = new javax.swing.JLabel();
        pn_dashboard4 = new ta8.PanelGabung();
        pn_hover4 = new ta8.PanelGabung();
        jsub = new javax.swing.JLabel();
        jsubkriteria = new javax.swing.JLabel();
        pn_dashboard5 = new ta8.PanelGabung();
        pn_hover5 = new ta8.PanelGabung();
        jAHP = new javax.swing.JLabel();
        jhitung = new javax.swing.JLabel();
        panelGradient2 = new ta8.PanelGradient();
        jLabel2 = new javax.swing.JLabel();
        pn_dashboard6 = new ta8.PanelGabung();
        pn_hover6 = new ta8.PanelGabung();
        jhasil = new javax.swing.JLabel();
        jkalkulator = new javax.swing.JLabel();
        pn_dashboard7 = new ta8.PanelGabung();
        pn_hover7 = new ta8.PanelGabung();
        jcetak = new javax.swing.JLabel();
        jprint = new javax.swing.JLabel();
        pn_dashboard8 = new ta8.PanelGabung();
        pn_hover8 = new ta8.PanelGabung();
        jpenilai = new javax.swing.JLabel();
        jnilaikaset = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLogout = new javax.swing.JLabel();
        mainPanel = new ta8.PanelGradient();
        blurWarna31 = new Blurwarna.BlurWarna3();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panelGradient1 = new ta8.PanelGradient();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelGabung1.setColorEnd(new java.awt.Color(0, 204, 204));
        panelGabung1.setColorStart(new java.awt.Color(0, 51, 153));

        pn_dashboard.setColorEnd(new java.awt.Color(0, 51, 153));
        pn_dashboard.setColorStart(new java.awt.Color(0, 102, 153));
        pn_dashboard.setRoundBottomLeft(20);
        pn_dashboard.setRoundBottomRight(20);
        pn_dashboard.setRoundTopLeft(20);
        pn_dashboard.setRoundTopRight(20);

        pn_hover.setColorEnd(new java.awt.Color(0, 51, 153));
        pn_hover.setColorStart(new java.awt.Color(0, 102, 153));
        pn_hover.setRoundBottomLeft(20);
        pn_hover.setRoundBottomRight(20);
        pn_hover.setRoundTopLeft(20);
        pn_hover.setRoundTopRight(20);

        jdashboard.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jdashboard.setForeground(new java.awt.Color(255, 255, 255));
        jdashboard.setText("Dashboard");
        jdashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jdashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jdashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jdashboardMouseExited(evt);
            }
        });

        jhome.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jhome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jhome.setIcon(new FlatSVGIcon("img/rumah.svg"));

        javax.swing.GroupLayout pn_hoverLayout = new javax.swing.GroupLayout(pn_hover);
        pn_hover.setLayout(pn_hoverLayout);
        pn_hoverLayout.setHorizontalGroup(
            pn_hoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_hoverLayout.createSequentialGroup()
                .addComponent(jhome, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jdashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pn_hoverLayout.setVerticalGroup(
            pn_hoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jhome, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout pn_dashboardLayout = new javax.swing.GroupLayout(pn_dashboard);
        pn_dashboard.setLayout(pn_dashboardLayout);
        pn_dashboardLayout.setHorizontalGroup(
            pn_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_hover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pn_dashboardLayout.setVerticalGroup(
            pn_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_hover, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MASTER DATA");

        pn_dashboard2.setColorEnd(new java.awt.Color(0, 51, 153));
        pn_dashboard2.setColorStart(new java.awt.Color(0, 51, 153));
        pn_dashboard2.setRoundBottomLeft(20);
        pn_dashboard2.setRoundBottomRight(20);
        pn_dashboard2.setRoundTopLeft(20);
        pn_dashboard2.setRoundTopRight(20);

        pn_hover2.setColorEnd(new java.awt.Color(0, 51, 153));
        pn_hover2.setColorStart(new java.awt.Color(0, 51, 153));
        pn_hover2.setRoundBottomLeft(20);
        pn_hover2.setRoundBottomRight(20);
        pn_hover2.setRoundTopLeft(20);
        pn_hover2.setRoundTopRight(20);

        jkaset.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jkaset.setForeground(new java.awt.Color(255, 255, 255));
        jkaset.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jkaset.setText("Data Kaset Game");
        jkaset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jkasetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jkasetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jkasetMouseExited(evt);
            }
        });

        jkasett.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jkasett.setIcon(new FlatSVGIcon("img/Cdgame.svg"));

        javax.swing.GroupLayout pn_hover2Layout = new javax.swing.GroupLayout(pn_hover2);
        pn_hover2.setLayout(pn_hover2Layout);
        pn_hover2Layout.setHorizontalGroup(
            pn_hover2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_hover2Layout.createSequentialGroup()
                .addComponent(jkasett, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jkaset, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        pn_hover2Layout.setVerticalGroup(
            pn_hover2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jkaset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jkasett, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pn_dashboard2Layout = new javax.swing.GroupLayout(pn_dashboard2);
        pn_dashboard2.setLayout(pn_dashboard2Layout);
        pn_dashboard2Layout.setHorizontalGroup(
            pn_dashboard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_hover2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pn_dashboard2Layout.setVerticalGroup(
            pn_dashboard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_hover2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pn_dashboard3.setColorEnd(new java.awt.Color(0, 51, 153));
        pn_dashboard3.setColorStart(new java.awt.Color(0, 51, 153));
        pn_dashboard3.setRoundBottomLeft(20);
        pn_dashboard3.setRoundBottomRight(20);
        pn_dashboard3.setRoundTopLeft(20);
        pn_dashboard3.setRoundTopRight(20);

        pn_hover3.setColorEnd(new java.awt.Color(0, 51, 153));
        pn_hover3.setColorStart(new java.awt.Color(0, 51, 153));
        pn_hover3.setRoundBottomLeft(20);
        pn_hover3.setRoundBottomRight(20);
        pn_hover3.setRoundTopLeft(20);
        pn_hover3.setRoundTopRight(20);

        jkriteria.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jkriteria.setForeground(new java.awt.Color(255, 255, 255));
        jkriteria.setText("Data Kriteria");
        jkriteria.setToolTipText("");
        jkriteria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jkriteriaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jkriteriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jkriteriaMouseExited(evt);
            }
        });

        jkriteriaa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jkriteriaa.setIcon(new FlatSVGIcon("img/datakriteria.svg"));

        javax.swing.GroupLayout pn_hover3Layout = new javax.swing.GroupLayout(pn_hover3);
        pn_hover3.setLayout(pn_hover3Layout);
        pn_hover3Layout.setHorizontalGroup(
            pn_hover3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_hover3Layout.createSequentialGroup()
                .addComponent(jkriteriaa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jkriteria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_hover3Layout.setVerticalGroup(
            pn_hover3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jkriteria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jkriteriaa, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pn_dashboard3Layout = new javax.swing.GroupLayout(pn_dashboard3);
        pn_dashboard3.setLayout(pn_dashboard3Layout);
        pn_dashboard3Layout.setHorizontalGroup(
            pn_dashboard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_hover3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pn_dashboard3Layout.setVerticalGroup(
            pn_dashboard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_hover3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pn_dashboard4.setColorEnd(new java.awt.Color(0, 51, 153));
        pn_dashboard4.setColorStart(new java.awt.Color(0, 51, 153));
        pn_dashboard4.setRoundBottomLeft(20);
        pn_dashboard4.setRoundBottomRight(20);
        pn_dashboard4.setRoundTopLeft(20);
        pn_dashboard4.setRoundTopRight(20);

        pn_hover4.setColorEnd(new java.awt.Color(0, 51, 153));
        pn_hover4.setColorStart(new java.awt.Color(0, 51, 153));
        pn_hover4.setRoundBottomLeft(20);
        pn_hover4.setRoundBottomRight(20);
        pn_hover4.setRoundTopLeft(20);
        pn_hover4.setRoundTopRight(20);

        jsub.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jsub.setIcon(new FlatSVGIcon("img/subkriteria.svg"));

        jsubkriteria.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jsubkriteria.setForeground(new java.awt.Color(255, 255, 255));
        jsubkriteria.setText("Data Sub Kriteria");
        jsubkriteria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jsubkriteriaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jsubkriteriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jsubkriteriaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_hover4Layout = new javax.swing.GroupLayout(pn_hover4);
        pn_hover4.setLayout(pn_hover4Layout);
        pn_hover4Layout.setHorizontalGroup(
            pn_hover4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_hover4Layout.createSequentialGroup()
                .addComponent(jsub, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsubkriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pn_hover4Layout.setVerticalGroup(
            pn_hover4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jsubkriteria, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pn_dashboard4Layout = new javax.swing.GroupLayout(pn_dashboard4);
        pn_dashboard4.setLayout(pn_dashboard4Layout);
        pn_dashboard4Layout.setHorizontalGroup(
            pn_dashboard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_hover4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pn_dashboard4Layout.setVerticalGroup(
            pn_dashboard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_hover4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pn_dashboard5.setColorEnd(new java.awt.Color(0, 51, 153));
        pn_dashboard5.setColorStart(new java.awt.Color(0, 51, 153));
        pn_dashboard5.setRoundBottomLeft(20);
        pn_dashboard5.setRoundBottomRight(20);
        pn_dashboard5.setRoundTopLeft(20);
        pn_dashboard5.setRoundTopRight(20);

        pn_hover5.setColorEnd(new java.awt.Color(0, 51, 153));
        pn_hover5.setColorStart(new java.awt.Color(0, 51, 153));
        pn_hover5.setRoundBottomLeft(20);
        pn_hover5.setRoundBottomRight(20);
        pn_hover5.setRoundTopLeft(20);
        pn_hover5.setRoundTopRight(20);

        jAHP.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jAHP.setForeground(new java.awt.Color(255, 255, 255));
        jAHP.setText("Perhitungan AHP");
        jAHP.setToolTipText("");
        jAHP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAHPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jAHPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jAHPMouseExited(evt);
            }
        });

        jhitung.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jhitung.setIcon(new FlatSVGIcon("img/penilaian.svg"));

        javax.swing.GroupLayout pn_hover5Layout = new javax.swing.GroupLayout(pn_hover5);
        pn_hover5.setLayout(pn_hover5Layout);
        pn_hover5Layout.setHorizontalGroup(
            pn_hover5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_hover5Layout.createSequentialGroup()
                .addComponent(jhitung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jAHP, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pn_hover5Layout.setVerticalGroup(
            pn_hover5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jAHP, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
            .addComponent(jhitung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pn_dashboard5Layout = new javax.swing.GroupLayout(pn_dashboard5);
        pn_dashboard5.setLayout(pn_dashboard5Layout);
        pn_dashboard5Layout.setHorizontalGroup(
            pn_dashboard5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_hover5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pn_dashboard5Layout.setVerticalGroup(
            pn_dashboard5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_hover5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelGradient2.setColorEnd(new java.awt.Color(0, 204, 255));
        panelGradient2.setColorStart(new java.awt.Color(51, 51, 255));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logotoko.png"))); // NOI18N

        javax.swing.GroupLayout panelGradient2Layout = new javax.swing.GroupLayout(panelGradient2);
        panelGradient2.setLayout(panelGradient2Layout);
        panelGradient2Layout.setHorizontalGroup(
            panelGradient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, Short.MAX_VALUE)
        );
        panelGradient2Layout.setVerticalGroup(
            panelGradient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, Short.MAX_VALUE)
        );

        pn_dashboard6.setColorEnd(new java.awt.Color(0, 51, 153));
        pn_dashboard6.setColorStart(new java.awt.Color(0, 51, 153));
        pn_dashboard6.setRoundBottomLeft(20);
        pn_dashboard6.setRoundBottomRight(20);
        pn_dashboard6.setRoundTopLeft(20);
        pn_dashboard6.setRoundTopRight(20);

        pn_hover6.setColorEnd(new java.awt.Color(0, 51, 153));
        pn_hover6.setColorStart(new java.awt.Color(0, 51, 153));
        pn_hover6.setRoundBottomLeft(20);
        pn_hover6.setRoundBottomRight(20);
        pn_hover6.setRoundTopLeft(20);
        pn_hover6.setRoundTopRight(20);

        jhasil.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jhasil.setForeground(new java.awt.Color(255, 255, 255));
        jhasil.setText("Perankingan");
        jhasil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jhasilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jhasilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jhasilMouseExited(evt);
            }
        });

        jkalkulator.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jkalkulator.setIcon(new FlatSVGIcon("img/kalkulator.svg"));

        javax.swing.GroupLayout pn_hover6Layout = new javax.swing.GroupLayout(pn_hover6);
        pn_hover6.setLayout(pn_hover6Layout);
        pn_hover6Layout.setHorizontalGroup(
            pn_hover6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_hover6Layout.createSequentialGroup()
                .addComponent(jkalkulator, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jhasil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_hover6Layout.setVerticalGroup(
            pn_hover6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jhasil, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(jkalkulator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pn_dashboard6Layout = new javax.swing.GroupLayout(pn_dashboard6);
        pn_dashboard6.setLayout(pn_dashboard6Layout);
        pn_dashboard6Layout.setHorizontalGroup(
            pn_dashboard6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_hover6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pn_dashboard6Layout.setVerticalGroup(
            pn_dashboard6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_hover6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pn_dashboard7.setColorEnd(new java.awt.Color(0, 51, 153));
        pn_dashboard7.setColorStart(new java.awt.Color(0, 51, 153));
        pn_dashboard7.setRoundBottomLeft(20);
        pn_dashboard7.setRoundBottomRight(20);
        pn_dashboard7.setRoundTopLeft(20);
        pn_dashboard7.setRoundTopRight(20);

        pn_hover7.setColorEnd(new java.awt.Color(0, 51, 153));
        pn_hover7.setColorStart(new java.awt.Color(0, 51, 153));
        pn_hover7.setRoundBottomLeft(20);
        pn_hover7.setRoundBottomRight(20);
        pn_hover7.setRoundTopLeft(20);
        pn_hover7.setRoundTopRight(20);

        jcetak.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jcetak.setForeground(new java.awt.Color(255, 255, 255));
        jcetak.setText("Cetak Laporan");
        jcetak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcetakMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jcetakMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jcetakMouseExited(evt);
            }
        });

        jprint.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jprint.setIcon(new FlatSVGIcon("img/kalkulator.svg"));

        javax.swing.GroupLayout pn_hover7Layout = new javax.swing.GroupLayout(pn_hover7);
        pn_hover7.setLayout(pn_hover7Layout);
        pn_hover7Layout.setHorizontalGroup(
            pn_hover7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_hover7Layout.createSequentialGroup()
                .addComponent(jprint, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcetak, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_hover7Layout.setVerticalGroup(
            pn_hover7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jcetak, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
            .addComponent(jprint, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pn_dashboard7Layout = new javax.swing.GroupLayout(pn_dashboard7);
        pn_dashboard7.setLayout(pn_dashboard7Layout);
        pn_dashboard7Layout.setHorizontalGroup(
            pn_dashboard7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_hover7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pn_dashboard7Layout.setVerticalGroup(
            pn_dashboard7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_hover7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pn_dashboard8.setColorEnd(new java.awt.Color(0, 51, 153));
        pn_dashboard8.setColorStart(new java.awt.Color(0, 51, 153));
        pn_dashboard8.setRoundBottomLeft(20);
        pn_dashboard8.setRoundBottomRight(20);
        pn_dashboard8.setRoundTopLeft(20);
        pn_dashboard8.setRoundTopRight(20);

        pn_hover8.setColorEnd(new java.awt.Color(0, 51, 153));
        pn_hover8.setColorStart(new java.awt.Color(0, 51, 153));
        pn_hover8.setRoundBottomLeft(20);
        pn_hover8.setRoundBottomRight(20);
        pn_hover8.setRoundTopLeft(20);
        pn_hover8.setRoundTopRight(20);

        jpenilai.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jpenilai.setForeground(new java.awt.Color(255, 255, 255));
        jpenilai.setText("Penilaian Kaset");
        jpenilai.setToolTipText("");
        jpenilai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpenilaiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpenilaiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpenilaiMouseExited(evt);
            }
        });

        jnilaikaset.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jnilaikaset.setIcon(new FlatSVGIcon("img/penilaian.svg"));

        javax.swing.GroupLayout pn_hover8Layout = new javax.swing.GroupLayout(pn_hover8);
        pn_hover8.setLayout(pn_hover8Layout);
        pn_hover8Layout.setHorizontalGroup(
            pn_hover8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_hover8Layout.createSequentialGroup()
                .addComponent(jnilaikaset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpenilai, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pn_hover8Layout.setVerticalGroup(
            pn_hover8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpenilai, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
            .addComponent(jnilaikaset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pn_dashboard8Layout = new javax.swing.GroupLayout(pn_dashboard8);
        pn_dashboard8.setLayout(pn_dashboard8Layout);
        pn_dashboard8Layout.setHorizontalGroup(
            pn_dashboard8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_hover8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pn_dashboard8Layout.setVerticalGroup(
            pn_dashboard8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_hover8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoutt.png"))); // NOI18N

        jLogout.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLogout.setText("Logout");
        jLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLogoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelGabung1Layout = new javax.swing.GroupLayout(panelGabung1);
        panelGabung1.setLayout(panelGabung1Layout);
        panelGabung1Layout.setHorizontalGroup(
            panelGabung1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGabung1Layout.createSequentialGroup()
                .addGroup(panelGabung1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGabung1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelGabung1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pn_dashboard3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pn_dashboard2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pn_dashboard4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pn_dashboard5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pn_dashboard7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pn_dashboard8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pn_dashboard6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelGabung1Layout.createSequentialGroup()
                        .addGroup(panelGabung1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelGabung1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelGabung1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelGabung1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(71, 71, 71))
                                    .addComponent(pn_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelGabung1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(38, 38, 38))
            .addGroup(panelGabung1Layout.createSequentialGroup()
                .addComponent(panelGradient2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelGabung1Layout.setVerticalGroup(
            panelGabung1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGabung1Layout.createSequentialGroup()
                .addComponent(panelGradient2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pn_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pn_dashboard2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_dashboard3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_dashboard4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_dashboard8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_dashboard5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_dashboard6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(pn_dashboard7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(panelGabung1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        getContentPane().add(panelGabung1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 600));

        mainPanel.setColorEnd(new java.awt.Color(0, 255, 255));
        mainPanel.setColorStart(new java.awt.Color(0, 51, 255));
        mainPanel.setPreferredSize(new java.awt.Dimension(870, 520));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SISTEM PENDUKUNG KEPUTUSAN PEMILIHAN ");

        jLabel10.setFont(new java.awt.Font("Baskerville Old Face", 3, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 102));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("MENGGUNAKAN METODE AHP");

        jLabel11.setFont(new java.awt.Font("Baskerville Old Face", 3, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 102));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("KASET GAME DI TOKO GS SHOP");

        javax.swing.GroupLayout blurWarna31Layout = new javax.swing.GroupLayout(blurWarna31);
        blurWarna31.setLayout(blurWarna31Layout);
        blurWarna31Layout.setHorizontalGroup(
            blurWarna31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blurWarna31Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(blurWarna31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, blurWarna31Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        blurWarna31Layout.setVerticalGroup(
            blurWarna31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blurWarna31Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(blurWarna31, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 630, 100));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logounindra.png"))); // NOI18N
        mainPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 110, 100));

        jLabel7.setFont(new java.awt.Font("Baskerville Old Face", 3, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("- Selamat Datang -");
        mainPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 340, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bgstadion.jpg"))); // NOI18N
        mainPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, 520));

        panelGradient1.setColorEnd(new java.awt.Color(0, 204, 204));
        panelGradient1.setColorStart(new java.awt.Color(0, 51, 153));

        jLabel8.setFont(new java.awt.Font("Baskerville Old Face", 3, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("- Sistem Pendukung Keputusan -");

        javax.swing.GroupLayout panelGradient1Layout = new javax.swing.GroupLayout(panelGradient1);
        panelGradient1.setLayout(panelGradient1Layout);
        panelGradient1Layout.setHorizontalGroup(
            panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGradient1Layout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
        );
        panelGradient1Layout.setVerticalGroup(
            panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGradient1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(panelGradient1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 870, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jdashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdashboardMouseEntered
        // TODO add your handling code here:
          pn_hover.setGradientColors(new Color(0,204,255), new Color(51,51,255));
          pn_hover.setHovered(true); // munculkan blur
          jdashboard.setForeground(Color.BLACK);
          setIconColor(Home, Color.WHITE);
          jdashboard.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jdashboardMouseEntered

    private void jdashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdashboardMouseExited
        // TODO add your handling code here:
         pn_hover.setGradientColors(new Color(0,51,153), new Color(0,102,153));
         pn_hover.setHovered(false); // hilangkan blur
         setIconColor(Home, Color.BLACK);
         jdashboard.setForeground(Color.WHITE);
    }//GEN-LAST:event_jdashboardMouseExited

    private void jkasetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jkasetMouseEntered
        // TODO add your handling code here:
          pn_hover2.setGradientColors(new Color(0,204,255), new Color(51,51,255));
          pn_hover2.setHovered(true); // munculkan blur
          jkaset.setForeground(Color.BLACK);
          setIconColor(Kaset, Color.WHITE);
          jkaset.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jkasetMouseEntered

    private void jkasetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jkasetMouseExited
        // TODO add your handling code here:
         pn_hover2.setGradientColors(new Color(0,51,153), new Color(0,102,153));
         pn_hover2.setHovered(false); // hilangkan blur
         jkaset.setForeground(Color.WHITE);
         setIconColor(Kaset, Color.BLACK);
    }//GEN-LAST:event_jkasetMouseExited

    private void jkriteriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jkriteriaMouseEntered
        // TODO add your handling code here:
         pn_hover3.setGradientColors(new Color(0,204,255), new Color(51,51,255));
         pn_hover3.setHovered(true); // munculkan blur
         jkriteria.setForeground(Color.BLACK);
         setIconColor(Kriteria, Color.WHITE);
         jkriteria.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jkriteriaMouseEntered

    private void jkriteriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jkriteriaMouseExited
        // TODO add your handling code here:
        pn_hover3.setGradientColors(new Color(0,51,153), new Color(0,102,153));
        pn_hover3.setHovered(false); // hilangkan blur
        jkriteria.setForeground(Color.WHITE);
        setIconColor(Kriteria, Color.BLACK);
    }//GEN-LAST:event_jkriteriaMouseExited

    private void jsubkriteriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jsubkriteriaMouseEntered
        // TODO add your handling code here:
         pn_hover4.setGradientColors(new Color(0,204,255), new Color(51,51,255));
         pn_hover4.setHovered(true); // munculkan blur
         jsubkriteria.setForeground(Color.BLACK);
          setIconColor(Sub, Color.WHITE);
         jsubkriteria.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jsubkriteriaMouseEntered

    private void jsubkriteriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jsubkriteriaMouseExited
        // TODO add your handling code here:
        pn_hover4.setGradientColors(new Color(0,51,153), new Color(0,102,153));
        pn_hover4.setHovered(false); // hilangkan blur
        jsubkriteria.setForeground(Color.WHITE);
         setIconColor(Sub, Color.BLACK);
    }//GEN-LAST:event_jsubkriteriaMouseExited

    private void jAHPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAHPMouseEntered
        // TODO add your handling code here:
         pn_hover5.setGradientColors(new Color(0,204,255), new Color(51,51,255));
         pn_hover5.setHovered(true); // munculkan blur
         jAHP.setForeground(Color.BLACK);
         setIconColor(Hitung, Color.WHITE);
         jAHP.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jAHPMouseEntered

    private void jAHPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAHPMouseExited
        // TODO add your handling code here:
        pn_hover5.setGradientColors(new Color(0,51,153), new Color(0,102,153));
        pn_hover5.setHovered(false); // hilangkan blur
        jAHP.setForeground(Color.WHITE);
        setIconColor(Hitung, Color.BLACK);
    }//GEN-LAST:event_jAHPMouseExited

    private void jhasilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jhasilMouseEntered
        // TODO add your handling code here:
         pn_hover6.setGradientColors(new Color(0,204,255), new Color(51,51,255));
         pn_hover6.setHovered(true); // munculkan blur
         jhasil.setForeground(Color.BLACK);
         setIconColor(Hasil, Color.WHITE);
         jhasil.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jhasilMouseEntered

    private void jhasilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jhasilMouseExited
        // TODO add your handling code here:
        pn_hover6.setGradientColors(new Color(0,51,153), new Color(0,102,153));
        pn_hover6.setHovered(false); // hilangkan blur
        jhasil.setForeground(Color.WHITE);
        setIconColor(Hasil, Color.BLACK);
    }//GEN-LAST:event_jhasilMouseExited

    private void jdashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdashboardMouseClicked
     MenuDashboard panel = new MenuDashboard();
     setMainPanel(panel);
    }//GEN-LAST:event_jdashboardMouseClicked

    private void jkriteriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jkriteriaMouseClicked
        // TODO add your handling code here:
     MenuKriteria panel = new MenuKriteria();
     setMainPanel(panel);
    }//GEN-LAST:event_jkriteriaMouseClicked

    private void jkasetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jkasetMouseClicked
        // TODO add your handling code here:
     MenuDataKaset panel = new MenuDataKaset();
     setMainPanel(panel);   
    }//GEN-LAST:event_jkasetMouseClicked

    private void jsubkriteriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jsubkriteriaMouseClicked
        // TODO add your handling code here:
     MenuSubKriteria panel = new MenuSubKriteria();
     setMainPanel(panel);   
    }//GEN-LAST:event_jsubkriteriaMouseClicked

    private void jAHPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAHPMouseClicked
        // TODO add your handling code here:
     AHP panel = new AHP();
     setMainPanel(panel);  
    }//GEN-LAST:event_jAHPMouseClicked

    private void jhasilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jhasilMouseClicked
        // TODO add your handling code here:
     HasilAkhir panel = new HasilAkhir();
     setMainPanel(panel);  
    }//GEN-LAST:event_jhasilMouseClicked

    private void jcetakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcetakMouseClicked
        // TODO add your handling code here:
     MenuLaporan panel = new MenuLaporan();
     setMainPanel(panel);  
    }//GEN-LAST:event_jcetakMouseClicked

    private void jcetakMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcetakMouseEntered
        // TODO add your handling code here:
          pn_hover7.setGradientColors(new Color(0,204,255), new Color(51,51,255));
          pn_hover7.setHovered(true); // munculkan blur
          jcetak.setForeground(Color.BLACK);
          setIconColor(Print, Color.WHITE);
          jcetak.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jcetakMouseEntered

    private void jcetakMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcetakMouseExited
        // TODO add your handling code here:
         pn_hover7.setGradientColors(new Color(0,51,153), new Color(0,102,153));
         pn_hover7.setHovered(false); // hilangkan blur
         setIconColor(Print, Color.BLACK);
         jcetak.setForeground(Color.WHITE);
    }//GEN-LAST:event_jcetakMouseExited

    private void jpenilaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpenilaiMouseClicked
        // TODO add your handling code here:
     MenuPenilaian panel = new MenuPenilaian();
     setMainPanel(panel);  
    }//GEN-LAST:event_jpenilaiMouseClicked

    private void jpenilaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpenilaiMouseEntered
        // TODO add your handling code here:
          pn_hover8.setGradientColors(new Color(0,204,255), new Color(51,51,255));
          pn_hover8.setHovered(true); // munculkan blur
          jpenilai.setForeground(Color.BLACK);
          setIconColor(Penilaian, Color.WHITE);
          jpenilai.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jpenilaiMouseEntered

    private void jpenilaiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpenilaiMouseExited
        // TODO add your handling code here:
         pn_hover8.setGradientColors(new Color(0,51,153), new Color(0,102,153));
         pn_hover8.setHovered(false); // hilangkan blur
         setIconColor(Penilaian, Color.BLACK);
         jpenilai.setForeground(Color.WHITE);
    }//GEN-LAST:event_jpenilaiMouseExited

    private void jLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLogoutMouseClicked
        // TODO add your handling code here:
         dispose();
        
        Login Login= new Login();
        Login.setVisible(true);
       
    }//GEN-LAST:event_jLogoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Blurwarna.BlurWarna3 blurWarna31;
    private javax.swing.JLabel jAHP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLogout;
    private javax.swing.JLabel jcetak;
    private javax.swing.JLabel jdashboard;
    private javax.swing.JLabel jhasil;
    private javax.swing.JLabel jhitung;
    private javax.swing.JLabel jhome;
    private javax.swing.JLabel jkalkulator;
    private javax.swing.JLabel jkaset;
    private javax.swing.JLabel jkasett;
    private javax.swing.JLabel jkriteria;
    private javax.swing.JLabel jkriteriaa;
    private javax.swing.JLabel jnilaikaset;
    private javax.swing.JLabel jpenilai;
    private javax.swing.JLabel jprint;
    private javax.swing.JLabel jsub;
    private javax.swing.JLabel jsubkriteria;
    private ta8.PanelGradient mainPanel;
    private ta8.PanelGabung panelGabung1;
    private ta8.PanelGradient panelGradient1;
    private ta8.PanelGradient panelGradient2;
    private ta8.PanelGabung pn_dashboard;
    private ta8.PanelGabung pn_dashboard2;
    private ta8.PanelGabung pn_dashboard3;
    private ta8.PanelGabung pn_dashboard4;
    private ta8.PanelGabung pn_dashboard5;
    private ta8.PanelGabung pn_dashboard6;
    private ta8.PanelGabung pn_dashboard7;
    private ta8.PanelGabung pn_dashboard8;
    private ta8.PanelGabung pn_hover;
    private ta8.PanelGabung pn_hover2;
    private ta8.PanelGabung pn_hover3;
    private ta8.PanelGabung pn_hover4;
    private ta8.PanelGabung pn_hover5;
    private ta8.PanelGabung pn_hover6;
    private ta8.PanelGabung pn_hover7;
    private ta8.PanelGabung pn_hover8;
    // End of variables declaration//GEN-END:variables

}