/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ta8;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableCellRenderer;
import static ta8.koneksi.koneksiDb;


public class HasilAkhir extends javax.swing.JPanel {
    Connection koneksi = null;
    private DefaultTableModel tabmode;
    protected KriteriaAhp pKriteria = new KriteriaAhp(); 
    protected  String kodeKaset;
    
    public HasilAkhir() {
        initComponents();
         koneksi = koneksi();
         dataTabel();
        Locale locale = new Locale ("id","ID");
       Locale.setDefault(locale);
        
    javax.swing.table.JTableHeader header = thasil.getTableHeader();
    javax.swing.table.DefaultTableCellRenderer renderer = 
        (javax.swing.table.DefaultTableCellRenderer) header.getDefaultRenderer();
    renderer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    
     DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        for (int i = 0; i < thasil.getColumnCount(); i++) {
            thasil.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
    }

    protected void dataTabel(){
        Object[] Baris = {"Ranking","Kode Kaset","Nama Kaset Game", "Hasil Penilaian"};
        tabmode = new DefaultTableModel(null, Baris);
        thasil.setModel(tabmode);

        String sql = "SELECT * FROM seleksi ORDER BY hasil_penilaian DESC";
        try{
            java.sql.Statement stat = koneksi.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            int i = 1;
            while(hasil.next()){
                String a = Integer.toString(i);
                String b = hasil.getString("kode_kaset");
                String c = hasil.getString("nama_kaset_game");
                String d = hasil.getString("hasil_penilaian");
                
                String[] data={a, b, c, d};
                tabmode.addRow(data);
                i++;
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
     private Connection koneksi(){
    try {
        Class.forName("com.mysql.jdbc.Driver");
        Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost/db_game","root","");
        return koneksi;
        
    }catch (Exception e){
        System.out.println("Koneksi Gagal:" + e.getMessage());
        return null;
    }
}
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        blurwarna1 = new Blurwarna.Blurwarna();
        scrollPaneWin111 = new scrollbar.ScrollPaneWin11();
        thasil = new javax.swing.JTable();
        btnhapus = new ta8.Buttonwarna();
        panelBlur1 = new ta8.PanelBlur();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        thasil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Ranking", "Kode Kaset", "Nama Kaset Game", "Genre", "Hasil Penilaian"
            }
        ));
        thasil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thasilMouseClicked(evt);
            }
        });
        scrollPaneWin111.setViewportView(thasil);

        javax.swing.GroupLayout blurwarna1Layout = new javax.swing.GroupLayout(blurwarna1);
        blurwarna1.setLayout(blurwarna1Layout);
        blurwarna1Layout.setHorizontalGroup(
            blurwarna1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blurwarna1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(scrollPaneWin111, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                .addContainerGap())
        );
        blurwarna1Layout.setVerticalGroup(
            blurwarna1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blurwarna1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneWin111, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(blurwarna1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 530, 230));

        btnhapus.setText("Hapus");
        btnhapus.setColorEnd(new java.awt.Color(255, 204, 0));
        btnhapus.setColorStart(new java.awt.Color(255, 0, 0));
        btnhapus.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnhapus.setHoverEnd(new java.awt.Color(204, 0, 204));
        btnhapus.setHoverStart(new java.awt.Color(255, 0, 0));
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 340, 110, 40));

        jLabel2.setFont(new java.awt.Font("SansSerif", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("~ Ranking Hasil Pemilihan Kaset Game ~");

        javax.swing.GroupLayout panelBlur1Layout = new javax.swing.GroupLayout(panelBlur1);
        panelBlur1.setLayout(panelBlur1Layout);
        panelBlur1Layout.setHorizontalGroup(
            panelBlur1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );
        panelBlur1Layout.setVerticalGroup(
            panelBlur1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(panelBlur1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 520, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bgPiala.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
          int ok = JOptionPane.showConfirmDialog(null,"hapus","Konfirmasi Dialog",JOptionPane.YES_NO_CANCEL_OPTION);
        if(ok == 0){
            String sql = "DELETE FROM seleksi WHERE kode_kaset='"+kodeKaset+"'";
            try{
                PreparedStatement stat = koneksi.prepareStatement(sql);

                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus ");
                dataTabel();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null,"Data gagal dihapus " + e);
            }
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void thasilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thasilMouseClicked
        // TODO add your handling code here:
        int bar = thasil.getSelectedRow();
        String a = tabmode.getValueAt(bar, 1).toString();
        kodeKaset = a;
    }//GEN-LAST:event_thasilMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Blurwarna.Blurwarna blurwarna1;
    private ta8.Buttonwarna btnhapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private ta8.PanelBlur panelBlur1;
    private scrollbar.ScrollPaneWin11 scrollPaneWin111;
    private javax.swing.JTable thasil;
    // End of variables declaration//GEN-END:variables
}
