/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ta8;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.*;

public class Login extends javax.swing.JFrame {
    

    public Login() {
        initComponents();
        setLocationRelativeTo(null); // Untuk Tampilan ke tengah Layar
        hidepass.setVisible(false);
        
    tuser.setText("Username");
    tuser.setForeground(new java.awt.Color(255,255,255));
    tuser.addFocusListener(new java.awt.event.FocusAdapter() {
        @Override
        public void focusGained(java.awt.event.FocusEvent evt) {
            if (tuser.getText().equals("Username")) {
                tuser.setText("");
                tuser.setForeground(new java.awt.Color(255,255,255));
            }
        }

        @Override
        public void focusLost(java.awt.event.FocusEvent evt) {
            if (tuser.getText().isEmpty()) {
                tuser.setText("Username");
                tuser.setForeground(new java.awt.Color(255,255,255));
            }
        }
    });

    // Placeholder untuk password (tpass)
    tpass.setText("Password");
    tpass.setEchoChar((char) 0); // Tampilkan teks biasa
    tpass.setForeground(new java.awt.Color(255,255,255));
    tpass.addFocusListener(new java.awt.event.FocusAdapter() {
        @Override
        public void focusGained(java.awt.event.FocusEvent evt) {
            if (new String(tpass.getPassword()).equals("Password")) {
                tpass.setText("");
                tpass.setForeground(new java.awt.Color(255,255,255));
                tpass.setEchoChar('•'); // Ganti dengan karakter password
            }
        }

        @Override
        public void focusLost(java.awt.event.FocusEvent evt) {
            if (new String(tpass.getPassword()).isEmpty()) {
                tpass.setText("Password");
                tpass.setForeground(new java.awt.Color(255,255,255));
                tpass.setEchoChar((char) 0); // Tampilkan teks biasa
            }
        }
    });
    
     btnlogin.requestFocus();
    }
    
 //Cek Login
  public void cek_login() {
    Connection kon = koneksi.koneksiDb();
    try {
        // PreparedStatement digunakan untuk mencegah SQL injection
        String sql = "SELECT * FROM logingame WHERE username=? AND password=?";
        PreparedStatement pst = kon.prepareStatement(sql);
        pst.setString(1, tuser.getText()); // Set username
        pst.setString(2, new String(tpass.getPassword())); // Set password (mengambil dari password field)

        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            Dashboard dashboard = new Dashboard();
            dashboard.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Login Gagal");
            tuser.setText("Username");
            tuser.setForeground(new java.awt.Color(153, 153, 153));
            
            // Reset placeholder untuk password
            tpass.setText("Password");
            tpass.setForeground(new java.awt.Color(153, 153, 153));
            tpass.setEchoChar((char) 0); // Tampilkan teks biasa

            tuser.requestFocus(); // Kembalikan fokus ke username
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, e);
    }
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        panelGradient2 = new ta8.PanelGradient();
        panelBlur1 = new ta8.PanelBlur();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tuser = new ta8.RoundTextField();
        jLabel4 = new javax.swing.JLabel();
        showpass = new javax.swing.JLabel();
        hidepass = new javax.swing.JLabel();
        tpass = new ta8.PasswordField();
        btnlogin = new ta8.Buttonwarna();
        close = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jregis = new javax.swing.JLabel();

        jPanel2.setName(""); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(846, 448));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelGradient2.setColorEnd(new java.awt.Color(255, 204, 51));
        panelGradient2.setColorStart(new java.awt.Color(204, 102, 0));
        panelGradient2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBlur1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGIN");
        panelBlur1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 120, 40));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("USERNAME");
        panelBlur1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        tuser.setForeground(new java.awt.Color(255, 255, 255));
        tuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuserActionPerformed(evt);
            }
        });
        panelBlur1.add(tuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 210, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PASSWORD");
        panelBlur1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 80, 30));

        showpass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showpass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Eye.png"))); // NOI18N
        showpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showpassMouseClicked(evt);
            }
        });
        panelBlur1.add(showpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 40, 30));

        hidepass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hidepass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Invisible.png"))); // NOI18N
        hidepass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hidepassMouseClicked(evt);
            }
        });
        panelBlur1.add(hidepass, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 40, 30));

        tpass.setForeground(new java.awt.Color(255, 255, 255));
        tpass.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        panelBlur1.add(tpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 210, -1));

        btnlogin.setText("Login\n");
        btnlogin.setColorEnd(new java.awt.Color(255, 0, 255));
        btnlogin.setColorStart(new java.awt.Color(0, 51, 153));
        btnlogin.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btnlogin.setHoverEnd(new java.awt.Color(204, 153, 0));
        btnlogin.setHoverStart(new java.awt.Color(153, 0, 153));
        btnlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnloginMouseEntered(evt);
            }
        });
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        panelBlur1.add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 210, 40));

        panelGradient2.add(panelBlur1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 410));

        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exitt.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
        });
        panelGradient2.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, 40, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bgloginbaru.jpg"))); // NOI18N
        panelGradient2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 550, 410));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ingin ganti Password ?");
        panelGradient2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, -1, 20));

        jregis.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jregis.setForeground(new java.awt.Color(255, 255, 255));
        jregis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jregis.setText("Register");
        jregis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jregisMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jregisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jregisMouseExited(evt);
            }
        });
        panelGradient2.add(jregis, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, -1, 20));

        getContentPane().add(panelGradient2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jregisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jregisMouseExited
        // TODO add your handling code here:
        jregis.setForeground(Color.WHITE);
    }//GEN-LAST:event_jregisMouseExited

    private void jregisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jregisMouseEntered
        // TODO add your handling code here:
        jregis.setForeground(new Color(51, 153, 255));  
        jregis.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jregisMouseEntered

    private void jregisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jregisMouseClicked
        // TODO add your handling code here:
        // Jika kamu sudah punya form register, panggil form tersebut
       
    }//GEN-LAST:event_jregisMouseClicked

    private void showpassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showpassMouseClicked
        // TODO add your handling code here:
        showpass.setVisible(false);
        hidepass.setVisible(true);
        tpass.setEchoChar((char)0);
       
    }//GEN-LAST:event_showpassMouseClicked

    private void hidepassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidepassMouseClicked
        // TODO add your handling code here:
        showpass.setVisible(true);
        hidepass.setVisible(false);
        tpass.setEchoChar('•');
       
    }//GEN-LAST:event_hidepassMouseClicked

    private void tuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tuserActionPerformed

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        // TODO add your handling code here:
         close.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_closeMouseEntered

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        // TODO add your handling code here:
        cek_login();
    }//GEN-LAST:event_btnloginActionPerformed

    private void btnloginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnloginMouseEntered
        // TODO add your handling code here:
         btnlogin.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnloginMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ta8.Buttonwarna btnlogin;
    private javax.swing.JLabel close;
    private javax.swing.JLabel hidepass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jregis;
    private ta8.PanelBlur panelBlur1;
    private ta8.PanelGradient panelGradient2;
    private javax.swing.JLabel showpass;
    private ta8.PasswordField tpass;
    private ta8.RoundTextField tuser;
    // End of variables declaration//GEN-END:variables

    private void addComponents() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
