/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ta8;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import java.util.Locale;
import javax.swing.UIDefaults;
import javax.swing.UIManager;
import scrollbar.ScrollBarWin11UI;
import static ta8.koneksi.koneksiDb;


public class MenuPenilaian extends javax.swing.JPanel {
    Connection koneksi = null;
    private DefaultTableModel tabmode;

    
    public MenuPenilaian() {
        UIDefaults ui = UIManager.getDefaults();
        ui.put("ScrollBarUI", ScrollBarWin11UI.class.getCanonicalName());
        initComponents();
        koneksi = koneksi(); 
        Locale locale = new Locale ("id","ID");
       Locale.setDefault(locale);
        kosong();
        aktif();
        datatable();
        getRelasiId();

    }
    
    protected void aktif(){
    ckode.requestFocus();
}
    
    protected void kosong(){
  tnama.setText("");
  crating.setSelectedIndex(0);
  charga.setSelectedIndex(0);
  ctarget.setSelectedIndex(0);
  cplatform.setSelectedIndex(0);
}
    
    protected void datatable(){
      Object[] Baris = {"Kode Kaset", "Nama Kaset Game", "Rating", "Harga", "Target Pemain", "Platform"};
      tabmode = new DefaultTableModel(null, Baris);
      tnilai.setModel(tabmode);
      String sql = "SELECT * FROM penilaian_kaset ORDER BY kode_kaset";
      try{
      java.sql.Statement stat = koneksi.createStatement();
      ResultSet hasil = stat.executeQuery(sql);
      while(hasil.next()){
              String a = hasil.getString("kode_kaset");
              String b = hasil.getString("nama_kaset_game");
              String c = hasil.getString("rating");
              String d = hasil.getString("harga");
              String e = hasil.getString("target_pemain");
              String f = hasil.getString("platform");

              String[] data={a, b, c, d, e, f};
              tabmode.addRow(data);
           }
              }catch(SQLException e){
              JOptionPane.showMessageDialog(null,e);
           }
           }
   
    public void getRelasiId(){
          String sql = "SELECT DISTINCT kode_kaset, nama_kaset_game FROM kaset_game ORDER BY kode_kaset";
          try{
          java.sql.Statement stat = koneksi.createStatement();
          ResultSet hasil = stat.executeQuery(sql);
          while(hasil.next()){
          String b = hasil.getString("kode_kaset");
          ckode.addItem(b);
        }
          }catch(SQLException e){
          JOptionPane.showMessageDialog(null,e);
         }
       }

    
       
     private Connection koneksi(){
    try {
        Class.forName("com.mysql.jdbc.Driver");
        Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost/db_game","root","");
        return koneksi;
        
    }catch (Exception e){
        System.out.println("Koneksi Gagal:" + e.getMessage());
        return null;
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        blurWarna41 = new Blurwarna.BlurWarna4();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ckode = new javax.swing.JComboBox<>();
        tnama = new ta8.RoundTextField();
        ctarget = new javax.swing.JComboBox<>();
        cplatform = new javax.swing.JComboBox<>();
        crating = new javax.swing.JComboBox<>();
        charga = new javax.swing.JComboBox<>();
        blurwarna1 = new Blurwarna.Blurwarna();
        scrollPaneWin111 = new scrollbar.ScrollPaneWin11();
        tnilai = new javax.swing.JTable();
        btnsimpan = new ta8.Buttonwarna();
        btnedit = new ta8.Buttonwarna();
        btnhapus = new ta8.Buttonwarna();
        btnbatal = new ta8.Buttonwarna();
        panelBlur1 = new ta8.PanelBlur();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kode Kaset");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Kaset Game");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Rating");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Harga");

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Target Pemain");

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Platform");

        ckode.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ckodeItemStateChanged(evt);
            }
        });
        ckode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckodeActionPerformed(evt);
            }
        });

        tnama.setForeground(new java.awt.Color(255, 255, 255));

        ctarget.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "~ Pilih Target Pemain ~", "Anak - Anak", "Remaja", "Dewasa" }));

        cplatform.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "~ Pilih Platform ~", "Playstation", "PC", "X-box" }));

        crating.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "~ Pilih Rating ~", "Sangat Tinggi", "Tinggi", "Sedang", "Rendah" }));

        charga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "~ Pilih Harga ~", "Murah", "Terjangkau", "Mahal", "Sangat Mahal" }));

        javax.swing.GroupLayout blurWarna41Layout = new javax.swing.GroupLayout(blurWarna41);
        blurWarna41.setLayout(blurWarna41Layout);
        blurWarna41Layout.setHorizontalGroup(
            blurWarna41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blurWarna41Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(blurWarna41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(blurWarna41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tnama, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(ckode, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crating, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47)
                .addGroup(blurWarna41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(65, 65, 65)
                .addGroup(blurWarna41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ctarget, 0, 161, Short.MAX_VALUE)
                    .addComponent(cplatform, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(charga, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35))
        );
        blurWarna41Layout.setVerticalGroup(
            blurWarna41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blurWarna41Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(blurWarna41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ckode)
                    .addComponent(jLabel5)
                    .addComponent(charga, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(blurWarna41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctarget, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(blurWarna41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(cplatform, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crating, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel1.add(blurWarna41, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 810, 170));

        tnilai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Kode Kaset", "Nama Kaset Game", "Rating", "Harga", "Target Pemain", "Platform"
            }
        ));
        tnilai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tnilaiMouseClicked(evt);
            }
        });
        scrollPaneWin111.setViewportView(tnilai);

        javax.swing.GroupLayout blurwarna1Layout = new javax.swing.GroupLayout(blurwarna1);
        blurwarna1.setLayout(blurwarna1Layout);
        blurwarna1Layout.setHorizontalGroup(
            blurwarna1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blurwarna1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(scrollPaneWin111, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
                .addContainerGap())
        );
        blurwarna1Layout.setVerticalGroup(
            blurwarna1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blurwarna1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneWin111, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(blurwarna1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 810, 190));

        btnsimpan.setText("Simpan");
        btnsimpan.setColorEnd(new java.awt.Color(0, 102, 153));
        btnsimpan.setColorStart(new java.awt.Color(102, 102, 102));
        btnsimpan.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnsimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsimpanMouseClicked(evt);
            }
        });
        jPanel1.add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 110, 40));

        btnedit.setText("Ubah");
        btnedit.setColorEnd(new java.awt.Color(0, 102, 153));
        btnedit.setColorStart(new java.awt.Color(102, 102, 102));
        btnedit.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnedit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btneditMouseClicked(evt);
            }
        });
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        jPanel1.add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 110, 40));

        btnhapus.setText("Hapus");
        btnhapus.setColorEnd(new java.awt.Color(204, 204, 0));
        btnhapus.setColorStart(new java.awt.Color(204, 0, 51));
        btnhapus.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnhapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhapusMouseClicked(evt);
            }
        });
        jPanel1.add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, 110, 40));

        btnbatal.setText("Batal");
        btnbatal.setColorEnd(new java.awt.Color(0, 102, 153));
        btnbatal.setColorStart(new java.awt.Color(102, 102, 102));
        btnbatal.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnbatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbatalMouseClicked(evt);
            }
        });
        jPanel1.add(btnbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 260, 110, 40));

        jLabel8.setFont(new java.awt.Font("SansSerif", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("~ Penilaian Kaset ~ ");

        javax.swing.GroupLayout panelBlur1Layout = new javax.swing.GroupLayout(panelBlur1);
        panelBlur1.setLayout(panelBlur1Layout);
        panelBlur1Layout.setHorizontalGroup(
            panelBlur1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBlur1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel8)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        panelBlur1Layout.setVerticalGroup(
            panelBlur1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(panelBlur1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 290, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bggow.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ckodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckodeActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btneditActionPerformed

    private void btnsimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsimpanMouseClicked
        // TODO add your handling code here:
        String sql = "insert into penilaian_kaset values (?,?,?,?,?,?)";
          try{
          PreparedStatement stat = koneksi.prepareStatement(sql);
          stat.setString(1, ckode.getSelectedItem().toString());
          stat.setString(2, tnama.getText());
          stat.setString(3, crating.getSelectedItem().toString());
          stat.setString(4, charga.getSelectedItem().toString());
          stat.setString(5, ctarget.getSelectedItem().toString());
          stat.setString(6, cplatform.getSelectedItem().toString());

          stat.executeUpdate();
          JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
          kosong();
          ckode.requestFocus();
        }
          catch (SQLException e){
          JOptionPane.showMessageDialog(null, "Data Gagal Disimpan"+e);
          }
          datatable();
    }//GEN-LAST:event_btnsimpanMouseClicked

    private void btneditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditMouseClicked
        // TODO add your handling code here:
        try{
        String sql = "update penilaian_kaset set nama_kaset_game=?, rating=?, harga=?, target_pemain=?, platform=? where kode_kaset='"+ckode.getSelectedItem()+"'";
        PreparedStatement stat = koneksi.prepareStatement(sql);
        stat.setString(1, tnama.getText());
        stat.setString(2, crating.getSelectedItem().toString());
        stat.setString(3, charga.getSelectedItem().toString());
        stat.setString(4, ctarget.getSelectedItem().toString());
        stat.setString(5, cplatform.getSelectedItem().toString());
        stat.executeUpdate();
        JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
        kosong();
        ckode.requestFocus();
      }
        catch (SQLException e){
        JOptionPane.showMessageDialog(null, "Data Gagal Diubah"+e);
      }
        datatable();
    }//GEN-LAST:event_btneditMouseClicked

    private void tnilaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tnilaiMouseClicked
        // TODO add your handling code here:
        int bar = tnilai.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        String e = tabmode.getValueAt(bar, 4).toString();
        String f = tabmode.getValueAt(bar, 5).toString();
        ckode.setSelectedItem(a);
        tnama.setText(b);
        crating.setSelectedItem(c);
        charga.setSelectedItem(d);
        ctarget.setSelectedItem(e);
        cplatform.setSelectedItem(f);

    }//GEN-LAST:event_tnilaiMouseClicked

    private void btnhapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhapusMouseClicked
        // TODO add your handling code here:
       int ok = JOptionPane.showConfirmDialog(null, "Yakin ingin menghapus data ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
    
    if (ok == JOptionPane.YES_OPTION) {
        try {
            int row = tnilai.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(null, "Pilih data di tabel yang ingin dihapus!");
                return;
            }

            String kodeKaset = tnilai.getValueAt(row, 0).toString(); 

            String sql = "DELETE FROM penilaian_kaset WHERE kode_kaset=?";
            PreparedStatement stat = koneksi.prepareStatement(sql);
            stat.setString(1, kodeKaset);
            int rowsAffected = stat.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
            } else {
                JOptionPane.showMessageDialog(null, "Gagal menghapus: kode tidak ditemukan");
            }

            kosong();
            datatable();
            ckode.requestFocus();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
        }
    }

    }//GEN-LAST:event_btnhapusMouseClicked

    private void btnbatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbatalMouseClicked
        // TODO add your handling code here:
        kosong();
        datatable();

    }//GEN-LAST:event_btnbatalMouseClicked

    private void ckodeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ckodeItemStateChanged
        // TODO add your handling code here:
        String sql = "SELECT DISTINCT nama_kaset_game FROM kaset_game WHERE kode_kaset='"+ckode.getSelectedItem().toString()+"';";
        try{
        java.sql.Statement stat = koneksi.createStatement();
        ResultSet hasil = stat.executeQuery(sql);
        while(hasil.next()){
        String b = hasil.getString("nama_kaset_game");
        tnama.setText(b);
      }
        }catch(SQLException e){
         JOptionPane.showMessageDialog(null,e);
       }
    }//GEN-LAST:event_ckodeItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Blurwarna.BlurWarna4 blurWarna41;
    private Blurwarna.Blurwarna blurwarna1;
    private ta8.Buttonwarna btnbatal;
    private ta8.Buttonwarna btnedit;
    private ta8.Buttonwarna btnhapus;
    private ta8.Buttonwarna btnsimpan;
    private javax.swing.JComboBox<String> charga;
    private javax.swing.JComboBox<String> ckode;
    private javax.swing.JComboBox<String> cplatform;
    private javax.swing.JComboBox<String> crating;
    private javax.swing.JComboBox<String> ctarget;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private ta8.PanelBlur panelBlur1;
    private scrollbar.ScrollPaneWin11 scrollPaneWin111;
    private ta8.RoundTextField tnama;
    private javax.swing.JTable tnilai;
    // End of variables declaration//GEN-END:variables
}
