/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ta8;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.BorderLayout;
import javax.swing.JFrame;
import java.io.File;
import java.sql.*;
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.util.Locale;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRParameter;
import static ta8.koneksi.koneksiDb;

/**
 *
 * @author USER
 */
public class MenuLaporan extends javax.swing.JPanel {
    Connection koneksi = null; 
    private FlatSVGIcon Kaset;
    private FlatSVGIcon Kriteria;
    private FlatSVGIcon Sub;
    private FlatSVGIcon Seleksi;
    private FlatSVGIcon Nilai;
  
  
    public MenuLaporan() {
        initComponents();
        
      
       Kaset = new FlatSVGIcon("img/Cdgame.svg", 96, 96); 
       jkasett.setIcon(Kaset);
       Kriteria = new FlatSVGIcon("img/datakriteria.svg", 96, 96); 
       jkriteriaa.setIcon(Kriteria);
       Sub = new FlatSVGIcon("img/iconChest.svg", 96, 96); 
       jsub.setIcon(Sub);
       Seleksi = new FlatSVGIcon("img/seleksi.svg", 96, 96); 
       jkalkulator.setIcon(Seleksi);
       Nilai = new FlatSVGIcon("img/iconpenilaian.svg", 96, 96); 
       jnilaikaset.setIcon(Nilai);
     
    }

   private void setIconColor(FlatSVGIcon icon, Color color) {
        icon.setColorFilter(new FlatSVGIcon.ColorFilter() {
            @Override
            public Color filter(Color c) {
                return color;
            }
        });
    }
   
   
    private Connection koneksi(){
    try {
        Class.forName("com.mysql.jdbc.Driver");
        Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost/db_game","root","");
        return koneksi;
        
    }catch (Exception e){
        System.out.println("Koneksi Gagal:" + e.getMessage());
        return null;
    }
}
    /**
     * Creates new form MenuLaporan
     */
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGradient1 = new ta8.PanelGradient();
        blurWarna61 = new Blurwarna.BlurWarna6();
        jkasett = new javax.swing.JLabel();
        jkriteriaa = new javax.swing.JLabel();
        jsub = new javax.swing.JLabel();
        jkalkulator = new javax.swing.JLabel();
        jnilaikaset = new javax.swing.JLabel();
        btnkriteria = new ta8.Buttonwarna();
        btndatakaset1 = new ta8.Buttonwarna();
        btndatasub = new ta8.Buttonwarna();
        btnpenilaian = new ta8.Buttonwarna();
        btnrankingan = new ta8.Buttonwarna();
        panelBlur1 = new ta8.PanelBlur();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        panelGradient1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        blurWarna61.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jkasett.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jkasett.setIcon(new FlatSVGIcon("img/Cdgame.svg"));
        blurWarna61.add(jkasett, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 118, 106));

        jkriteriaa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jkriteriaa.setIcon(new FlatSVGIcon("img/datakriteria.svg"));
        blurWarna61.add(jkriteriaa, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 119, 106));

        jsub.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jsub.setIcon(new FlatSVGIcon("img/subkriteria.svg"));
        blurWarna61.add(jsub, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 175, 118, 100));

        jkalkulator.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jkalkulator.setIcon(new FlatSVGIcon("img/kalkulator.svg"));
        blurWarna61.add(jkalkulator, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 119, 100));

        jnilaikaset.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jnilaikaset.setIcon(new FlatSVGIcon("img/penilaian.svg"));
        blurWarna61.add(jnilaikaset, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 120, 100));

        btnkriteria.setText("Cetak Data Kriteria");
        btnkriteria.setColorEnd(new java.awt.Color(153, 153, 255));
        btnkriteria.setColorStart(new java.awt.Color(0, 0, 102));
        btnkriteria.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnkriteria.setHoverEnd(new java.awt.Color(153, 153, 255));
        btnkriteria.setHoverStart(new java.awt.Color(0, 0, 102));
        btnkriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkriteriaActionPerformed(evt);
            }
        });
        blurWarna61.add(btnkriteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 200, 40));

        btndatakaset1.setText("Cetak Data Kaset Game");
        btndatakaset1.setColorEnd(new java.awt.Color(153, 153, 255));
        btndatakaset1.setColorStart(new java.awt.Color(0, 0, 102));
        btndatakaset1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btndatakaset1.setHoverEnd(new java.awt.Color(153, 153, 255));
        btndatakaset1.setHoverStart(new java.awt.Color(0, 0, 102));
        btndatakaset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndatakaset1ActionPerformed(evt);
            }
        });
        blurWarna61.add(btndatakaset1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 200, 40));

        btndatasub.setText("Cetak Data Sub Kriteria");
        btndatasub.setColorEnd(new java.awt.Color(153, 153, 255));
        btndatasub.setColorStart(new java.awt.Color(0, 0, 102));
        btndatasub.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btndatasub.setHoverEnd(new java.awt.Color(153, 153, 255));
        btndatasub.setHoverStart(new java.awt.Color(0, 0, 102));
        btndatasub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndatasubActionPerformed(evt);
            }
        });
        blurWarna61.add(btndatasub, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 200, 40));

        btnpenilaian.setText("Cetak Penilaian Kaset");
        btnpenilaian.setColorEnd(new java.awt.Color(153, 153, 255));
        btnpenilaian.setColorStart(new java.awt.Color(0, 0, 102));
        btnpenilaian.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnpenilaian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpenilaianActionPerformed(evt);
            }
        });
        blurWarna61.add(btnpenilaian, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 200, 40));

        btnrankingan.setText("Cetak Perankingan");
        btnrankingan.setColorEnd(new java.awt.Color(153, 153, 255));
        btnrankingan.setColorStart(new java.awt.Color(0, 0, 102));
        btnrankingan.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnrankingan.setHoverEnd(new java.awt.Color(153, 153, 255));
        btnrankingan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrankinganActionPerformed(evt);
            }
        });
        blurWarna61.add(btnrankingan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 210, 40));

        panelGradient1.add(blurWarna61, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 460, 500));

        jLabel1.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("~ Laporan ~");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout panelBlur1Layout = new javax.swing.GroupLayout(panelBlur1);
        panelBlur1.setLayout(panelBlur1Layout);
        panelBlur1Layout.setHorizontalGroup(
            panelBlur1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBlur1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        panelBlur1Layout.setVerticalGroup(
            panelBlur1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        panelGradient1.add(panelBlur1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 230, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bglapor.jpg"))); // NOI18N
        panelGradient1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradient1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradient1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnkriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkriteriaActionPerformed
        // TODO add your handling code here:
           try {
        String namaFile = "src/Laporan/LaporanKriteria.jasper";
        Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost/db_game","root",""); 
        HashMap<String, Object> parameter = new HashMap<>();
        parameter.put(JRParameter.REPORT_LOCALE, new Locale("id", "ID"));
        File report_file = new File(namaFile);
        if (report_file.exists()) {
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, koneksi);
            JasperViewer.viewReport(jasperPrint, false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        } else {
            JOptionPane.showMessageDialog(null, "File laporan tidak ditemukan.");
        }
    } catch (JRException e) {
        JOptionPane.showMessageDialog(null, "Error loading report: " + e.getMessage());
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
     }    
    }//GEN-LAST:event_btnkriteriaActionPerformed

    private void btndatakaset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndatakaset1ActionPerformed
        // TODO add your handling code here:
         try {
        String namaFile = "src/Laporan/LaporanDataKaset.jasper";
        Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost/db_game","root",""); 
        HashMap<String, Object> parameter = new HashMap<>();
        parameter.put(JRParameter.REPORT_LOCALE, new Locale("id", "ID"));
        File report_file = new File(namaFile);
        if (report_file.exists()) {
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, koneksi);
            JasperViewer.viewReport(jasperPrint, false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        } else {
            JOptionPane.showMessageDialog(null, "File laporan tidak ditemukan.");
        }
    } catch (JRException e) {
        JOptionPane.showMessageDialog(null, "Error loading report: " + e.getMessage());
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
     }    
    }//GEN-LAST:event_btndatakaset1ActionPerformed

    private void btndatasubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndatasubActionPerformed
        // TODO add your handling code here:
         try {
        String namaFile = "src/Laporan/LaporanSub.jasper";
        Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost/db_game","root",""); 
        HashMap<String, Object> parameter = new HashMap<>();
        parameter.put(JRParameter.REPORT_LOCALE, new Locale("id", "ID"));
        File report_file = new File(namaFile);
        if (report_file.exists()) {
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, koneksi);
            JasperViewer.viewReport(jasperPrint, false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        } else {
            JOptionPane.showMessageDialog(null, "File laporan tidak ditemukan.");
        }
    } catch (JRException e) {
        JOptionPane.showMessageDialog(null, "Error loading report: " + e.getMessage());
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
     }    
    }//GEN-LAST:event_btndatasubActionPerformed

    private void btnpenilaianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpenilaianActionPerformed
        // TODO add your handling code here:
          try {
        String namaFile = "src/Laporan/LaporanPenilaian.jasper";
        Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost/db_game","root",""); 
        HashMap<String, Object> parameter = new HashMap<>();
        parameter.put(JRParameter.REPORT_LOCALE, new Locale("id", "ID"));
        File report_file = new File(namaFile);
        if (report_file.exists()) {
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, koneksi);
            JasperViewer.viewReport(jasperPrint, false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        } else {
            JOptionPane.showMessageDialog(null, "File laporan tidak ditemukan.");
        }
    } catch (JRException e) {
        JOptionPane.showMessageDialog(null, "Error loading report: " + e.getMessage());
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
     }    
    }//GEN-LAST:event_btnpenilaianActionPerformed

    private void btnrankinganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrankinganActionPerformed
        // TODO add your handling code here:
         try {
        String namaFile = "src/Laporan/LaporanRanking.jasper";
        Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost/db_game","root",""); 
        HashMap<String, Object> parameter = new HashMap<>();
        parameter.put(JRParameter.REPORT_LOCALE, new Locale("id", "ID"));
        File report_file = new File(namaFile);
        if (report_file.exists()) {
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, koneksi);
            JasperViewer.viewReport(jasperPrint, false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        } else {
            JOptionPane.showMessageDialog(null, "File laporan tidak ditemukan.");
        }
    } catch (JRException e) {
        JOptionPane.showMessageDialog(null, "Error loading report: " + e.getMessage());
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
     }    
    }//GEN-LAST:event_btnrankinganActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Blurwarna.BlurWarna6 blurWarna61;
    private ta8.Buttonwarna btndatakaset1;
    private ta8.Buttonwarna btndatasub;
    private ta8.Buttonwarna btnkriteria;
    private ta8.Buttonwarna btnpenilaian;
    private ta8.Buttonwarna btnrankingan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jkalkulator;
    private javax.swing.JLabel jkasett;
    private javax.swing.JLabel jkriteriaa;
    private javax.swing.JLabel jnilaikaset;
    private javax.swing.JLabel jsub;
    private ta8.PanelBlur panelBlur1;
    private ta8.PanelGradient panelGradient1;
    // End of variables declaration//GEN-END:variables
}
